#+title: Guix Development Environments
#+options: toc:nil

Useful development environments for software projects.

* What I Want
Consider the directory with the following contents.

1. A normal haskell cabal project.
2. =guix.scm=

The =guix.scm= file looks like this.

#+begin_src scheme
(define %source-dir
    (dirname (current-filename)))

(define ghc-graphdoc
    (package
     (name "ghc-graphdoc")
     (version "0.0.1")
     (source
      (local-file %source-dir
                  #:recursive? #t
                  #:select? (git-predicate %source-dir)))
     (build-system haskell-build-system)
     (inputs
      (list ghc-pandoc
            ghc-pandoc-types))
     (home-page "")
     (synopsis "")
     (description "")
     (license license:gpl3+)))

;; The new part:
(development-environment
  (for ghc-graphdoc))
#+end_src

A development-environment extends the concept of a normal development profile for a package defined by =package->development-manifest=. It should allow me to do the following:

1. Activate the development environment profile.
2. In that profile, build the program.

   #+begin_src shell
   cabal build
   cabal repl
   #+end_src

   By default, these would use a ghc package database generated by guix.

** Extra Desires

1. Disable dependence on Guix packages.
2. Add extra packages into the development environment.
3. Enhance the development environment with extra add-ons which are parameterized by the rest of the development environment. Like an "lsp" add-on which adds the appropriate language server.
